# =====================================================
# 教學生態系感知蓝图 - Netlify 部署配置
# =====================================================

[build]
  # 建置命令
  command = "npm run build"
  
  # Next.js 插件會自動處理輸出目錄
  # publish = ".next"  # 移除此行，讓插件自動處理
  
  # 建置環境
  environment = { NODE_VERSION = "18", NODE_ENV = "production" }

# Next.js 插件配置
[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.processing]
  # 自動優化
  skip_processing = false

[build.processing.css]
  # CSS 最小化
  bundle = true
  minify = true

[build.processing.js]
  # JavaScript 最小化
  bundle = true
  minify = true

[build.processing.html]
  # HTML 最小化
  pretty_urls = true

[build.processing.images]
  # 圖片優化
  compress = true

# =====================================================
# 重定向規則 (Next.js App Router 支持)
# =====================================================

[[redirects]]
  # API 代理到 Supabase
  from = "/api/*"
  to = "https://imidprdspztfqabdzqrr.supabase.co/rest/v1/:splat"
  status = 200
  headers = { X-From = "Netlify" }

[[redirects]]
  # 認證回調
  from = "/auth/callback"
  to = "/auth/callback"
  status = 200

# Next.js 插件會自動處理客戶端路由，移除錯誤的重定向

# =====================================================
# Headers 安全配置
# =====================================================

[[headers]]
  for = "/*"
  [headers.values]
    # 安全標頭
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # 內容安全策略
    Content-Security-Policy = '''
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://cdn.jsdelivr.net;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com;
      font-src 'self' https://fonts.gstatic.com;
      img-src 'self' data: https: blob:;
      connect-src 'self' https://imidprdspztfqabdzqrr.supabase.co wss://imidprdspztfqabdzqrr.supabase.co;
      media-src 'self' blob:;
    '''
    
    # 快取控制
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# =====================================================
# 環境特定設定
# =====================================================

[context.production]
  command = "npm run build"
  environment = { NODE_ENV = "production" }

[context.branch-deploy]
  command = "npm run build"
  
[context.deploy-preview]
  command = "npm run build"

# =====================================================
# 表單處理 (未來功能)
# =====================================================

[forms]
  # 啟用 Netlify Forms (如聯絡表單)
  enabled = true

# =====================================================
# 函數配置 (Serverless Functions)
# =====================================================

[functions]
  # Netlify Functions 目錄
  directory = "netlify/functions"
  
  # Node.js 運行時
  node_bundler = "esbuild"